import Head from 'next/head'
import Drawer from "../components/drawer"
import Navbar from "../components/navbar"
import Carousel from "../components/carousel"
import SidePanel from '@/components/panels/sidePanel'
import MainPanel from '@/components/panels/mainPanel'
import Shortcuts from '@/components/panels/shortcuts'
import { useEffect, useState } from 'react'
import axios from 'axios'


export default function Home() {
  const [bar, setBar] = useState(1);
  const [d, setData] = useState({})
  async function getData() {
    let data = await axios.get("https://expressapi2.onrender.com/property")
    data = data.data[0]
    setData((d) => d = data)
  }
  useEffect(()=>{
    // setData(d => d = getData())
    // console.log("function: ", getData());
    getData()
  }, [])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='p-0 flex'>
        <Drawer bar={bar}/>
        <div>
          <Navbar bar={bar}/>
          <Carousel/>
          <div className='panels my-4 justify-between md:flex'>
            <SidePanel d = {d}/>
            <MainPanel d = {d}/>
            <Shortcuts/>
          </div>
        </div>
      </main>
    </>
  )
}
